import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { CopilotKitProvider } from "@copilotkitnext/react";
import "@copilotkitnext/react/styles.css";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CopilotKitProvider
          runtimeUrl="/api/copilotkit"
          showDevConsole={true}>
          {children}
        </CopilotKitProvider>
      </body>
    </html>
  );
}
